# Generated by Django 5.1.1 on 2024-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nsukindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
